version: '3'
services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - authenticationNet
      - adminNet
      - customerNet
      - daemonNet
      - managerNet
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - daemonNet
      - managerNet

  authenticationDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
    volumes:
    - authenticationdbdata:/var/lib/mysql
    networks:
      - authenticationNet
  authenticationDBMigration:
    image: authenticationdbmigration
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      authenticationDB:
        condition: service_healthy
    networks:
      - authenticationNet
  authentication:
    image: authentication
    environment:
      - DATABASE_URL=authenticationDB
    depends_on:
      - authenticationDBMigration
    ports:
    - 5000:5000
    networks:
      - authenticationNet


  shopDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    volumes:
      - shopdbdata:/var/lib/mysql
    networks:
      - adminNet
      - customerNet
      - daemonNet

  shopDBMigration:
    image: shopdbmigration
    environment:
      - DATABASE_URL=shopDB
    depends_on:
      shopDB:
        condition: service_healthy
    networks:
      - adminNet

  manager:
    image: manager
    environment:
      - REDIS_URL=redis
    depends_on:
      - redis
    ports:
      - 5001:5001
    networks:
      - managerNet

  daemon:
    image: daemon
    environment:
      - DATABASE_URL=shopDB
      - REDIS_URL=redis
    depends_on:
      - shopDBMigration
      - redis
    networks:
      - daemonNet

  customer:
    image: customer
    environment:
      - DATABASE_URL=shopDB
    depends_on:
      - shopDBMigration
    ports:
      - 5002:5002
    networks:
      - customerNet

  admin:
    image: admin
    environment:
      - DATABASE_URL=shopDB
    depends_on:
      - shopDBMigration
    ports:
      - 5003:5003
    networks:
      - adminNet
volumes:
  authenticationdbdata:
  shopdbdata:
networks:
  authenticationNet:
  adminNet:
  customerNet:
  managerNet:
  daemonNet:

#-pregled hard diskova u power shellu
#docker volume ls(prikaz svih hard diskova)
#docker volume inspect v6_dbdata(info o nekom)

#izlistavanje svih mreza
#docker network ls
#docker network inspect imeMreze